---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oci-repository.yaml
  - middleware.yaml
  - pvc/
  - sabnzbd/
  - radarr/
  - sonarr/
  - bazarr/
  - prowlarr/
  - deluge/
  - jellyfin/
  - jellyseerr/
