---
# =============================================================================
# Technitium DNS Server Handlers
# =============================================================================

- name: Restart technitium
  ansible.builtin.systemd:
    name: "{{ technitium_service_name }}"
    state: restarted
    daemon_reload: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
