---
apiVersion: v1
kind: ConfigMap
metadata:
  name: climate-ref-esmvaltool-config
  namespace: climate-ref
data:
  config.yaml: |
    max_parallel_tasks: 2
    dask:
      use: local_distributed
      profiles:
        local_distributed:
          cluster:
            type: distributed.LocalCluster
            n_workers: 1
            threads_per_worker: 2
            memory_limit: 4GiB
