apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: climate-ref
resources:
  - namespace.yaml
  - configmap-esmvaltool.yaml
  - helmrelease.yaml
  - httproute.yaml
  - middleware.yaml
  - pvc/
  - esgpull/
  - jobs/
  - monitoring/
  - autoscaling/
