apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/production/security
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
    - name: storage
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
