apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-routes/
  - homepage/
  - podinfo/
  - media/
  - climate-ref/
  - github-runners/
  # Disabled apps in ./disabled/ directory
