apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - authelia.yaml
  - authelia-secrets.yaml
  - users-database.yaml
  - httproute.yaml
