apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo
patches:
  - target:
      kind: HelmRelease
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/values/ingress/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: podinfo.staging.home.lewelly.com
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: podinfo.staging.home.lewelly.com
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: podinfo.staging.home.lewelly.com
