---
apiVersion: v1
kind: Service
metadata:
  name: actions-cache-server
  namespace: github-runners
  labels:
    app.kubernetes.io/name: actions-cache-server
spec:
  selector:
    app.kubernetes.io/name: actions-cache-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
