apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-gateway/
  - traefik/
  - external-dns/
  - metrics-server/
  - pull-secrets/
  - technitium-rbac/
  - reloader/
  - tuppr/
