apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- external-dns.yaml
- tsig-secret.yaml
# cloudflare-token.yaml removed - no longer using Cloudflare provider

