apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - homepage.yaml
  - homepage-secret.yaml
  - configmap.yaml
  - rbac.yaml
  - httproute.yaml
