apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-default.yaml
  - loki.yaml
  - tempo.yaml
  - prometheus.yaml
  - grafana.yaml
  - alertmanager.yaml
  - prometheus-adapter.yaml
