apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: ha.home.lewelly.com
  tls:
    - hosts:
        - ha.home.lewelly.com
      secretName: home-assistant-tls-secret
  rules:
  - host: ha.home.lewelly.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
  ingressClassName: nginx
