apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
type: Opaque
stringData:
  user_key: ENC[AES256_GCM,data:/Q+NQpE6//LzwN2UfMrgt0NhAQUlm8jJa/aYec+q,iv:KONFEry9KHmJVS6jEb9wBMfJi95NxzQi2FFRzhOt69M=,tag:2G2+ZU5hWgJsNeqjgjmzDQ==,type:str]
  api_token: ENC[AES256_GCM,data:Sev6txaNOCMQpEanM2WDwOyfwxLxPiWB8LcN0url,iv:8QSWMR/9NoxJJMs+WUiUtN2Z4CfasHkRXsPrylsQCTQ=,tag:S3Zy8Ih+DHjXVGkClLTu/Q==,type:str]
sops:
  lastmodified: "2025-12-26T10:37:50Z"
  mac: ENC[AES256_GCM,data:/XniFYhJ8tK1S5g18x+dm3DoVTIPMM9bQkSGsnzArA4IOu0xK3986XdB/kIvXO6wu3W7F75WWkjTbTDvcRdllXWbUC8vXOS20NG+KR79Fj5P5adX2aP6rdAzMsXU50u3LUNIASJ/6uIAGBxf2C+ZpRmWexO3BwPFnHtUlI9nKcs=,iv:KCPtLyrdmLayj0NquYWtY+kkqgiktdiqlgjG/3hNA4o=,tag:wMRNOBp1bPg5azq5X0ASsQ==,type:str]
  pgp:
    - created_at: "2025-12-26T10:37:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAtXPwLxzhZ+8wCOYSCKuwj208ebT4JWfcBSUyzTKVF3Iw
        E7WaQ515Xm0BwvGUEg9n4ec7wcTsjYkT3qQypLpS7RwJ8P9CMRY5TZUp5LtTO78k
        1GYBCQIQ18N1zyLo6qEKSj/bK1ESyNMIm7Vi36xwv+Jwh6KwveA42RWf8nWZoiLq
        USKJbYSCMjisQ5tqQ04gZYa39Jg54vgVqUXVcoHrBDprj2cSjc6XQDR9QErpSTBO
        ZD10mjFYLpc=
        =jGb5
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
