apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:sp0BEG0=,iv:O38NleTH9FOWoTfmkolHgW5GGClbBF4HGqWG6+LM/r0=,tag:oUm//TyoTQMeARg9avEAYQ==,type:str]
  admin-password: ENC[AES256_GCM,data:tQ2a2VLaAqaZembxoAs=,iv:VHUTSiVosRQC/VVW6IQTWaAq3Slnnp+wU+3HuSfk96w=,tag:BN+2AuVUQEYE1tTbaNpFoQ==,type:str]
sops:
  lastmodified: "2025-12-26T10:21:28Z"
  mac: ENC[AES256_GCM,data:1qIbHvNGOxIrdx/Rs+dauCV/AdCyPqdKnGg1S3Kd6Lsw7tIlviYwdN8Lcmxe4HeVqe43qJ99lL0DQhUEWXi3EnJesa+OwRFBeJ/TfgOjh4K01lHCyhj2O+MRzZC3ZPz/uiBJmafUWv4zY9j+LeYEYzEWN30DDtxlPlxTzA3R7yY=,iv:xtVFAwVSSDDN8XEVXjwd+MEpaa1BeEEOM/Ifgu7luZ0=,tag:l3mQeL9NfgEQYC0X+jHkEQ==,type:str]
  pgp:
    - created_at: "2025-12-26T10:21:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAwhYFQzWYgt7sCcq/MxWLQeYg3MHvX4p8PwEZAshNRmcw
        mF8PDlumbRpoMDfncfFaGt/115XPBn1SYJx7QFUIj5gTBBFWoCNF/b57NxUjAnrJ
        1GgBCQIQqfRGANRfiwWz7QsqpfRrJ/XBDXAHdYlSp8WaW0siqLssW2zY+daHD2V9
        q+QCqGjLSbk27Ud3XawmJ+3Sc8xYVByTj+YZTWVHv3LIKq1C/LWVxLVHW2BWwXVh
        5DVHzO5IfdKh/A==
        =1+LA
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
