apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cc78YGN53fJlcqjzDVwCcpTxf3moZLq2QPtQyh7qLgoQpbBH8LsJ0dwR56A5OSEIh76yfvdQHySjJJ6rLnxlzw==,iv:SpXnX+AL7fexvT9vFnKpmeyn+vDNxsmP16N+Nbs1TpA=,tag:8F5OdFn5jjGGTZhuPSqbGQ==,type:str]
sops:
  lastmodified: "2025-12-27T00:59:19Z"
  mac: ENC[AES256_GCM,data:lKEqLFX81la2jWyMZAzamq8wflhEBWFv5xwFmppfEcOvaaGnGRyA6YaCAYZDw/MNACoBXtLyV2KtJtYbW68BqlDXnY4LnNTEkA664CrgU+NHNDGWDmioW2wrND7auddr/RdFAGZeXn19aB0sL/hakeWYELVXdHhhCl7T4hhc7Co=,iv:QiHtzkYRtou0NCe5q9M+XNSRQ8OOr3tf9Ef+ENsxPsw=,tag:ynZVo79s437t7JEUTYDnOA==,type:str]
  pgp:
    - created_at: "2025-12-27T00:22:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAJzwKjYXaN758Z3wbOIMWosfJhocq+goqLy/47QUXHQsw
        pPrYJXS9WidDRbTAkWsxf+GLfCjWjBafgvrF+TJI0sGgzqroD/16w8KHkFNJycvY
        1GgBCQIQ80Bnx5Si5JQKfraxRosodxP2/7M4j2ZHzpVaxPzM22FwxhRzGvlaNYWp
        m9BjD+uqDkncHaqlyLOH28bNd5Ggh7LdCOWqD8EbKSXuamD5IN/IckdxCiR7lBiG
        9YuYoynGK3EXsw==
        =UrOm
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
