apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-secret.yaml
  - alerting-rules.yaml
  - grafana-secret.yaml
  - grafana-oidc-secret.yaml
  - kube-prometheus-stack.yaml
