apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/external-dns
patches:
  - target:
      kind: HelmRelease
      name: external-dns
    patch: |-
      - op: replace
        path: /spec/values/domainFilters
        value:
          - staging.home.lewelly.com
          - vela.lewelly.com
